#!/bin/bash
#
#  Copyright (c) 2020 DefKorns (https://defkorns.github.io/LICENSE)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
pe_dir="/media/project_eris"
es_dir="${pe_dir}/opt/emulationstation"
psx_gamelist="${pe_dir}/opt/emulationstation/.emulationstation/gamelists/psx"
sup_dir="${pe_dir}/etc/project_eris/SUP"
prev_version="${sup_dir}/emulationstation/playlist_es.sh"
backup_file="${es_dir}/launch.backup"
launcher="${es_dir}/launch.sh"

[ -f "${prev_version}" ] && rm -rf "${prev_version}"
[ -f "${backup_file}" ] && rm -rf "${backup_file}"
[ -f "${launcher}" ] && sed -i '/playlist_es.sh/d' "${launcher}"
[ -f "${psx_gamelist}/gamelist.xml" ] && rm -rf "${psx_gamelist}/gamelist.xml"
[ -d "${psx_gamelist}/media" ] && rm -rf "${psx_gamelist:?}/media"
