#!/bin/bash
#
#  Copyright (c) 2020 DefKorns (https://defkorns.github.io/LICENSE)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
pe_dir="/media/project_eris"
es_dir="${pe_dir}/opt/emulationstation"
sup_dir="${pe_dir}/etc/project_eris/SUP"
prev_version="${sup_dir}/emulationstation/playlist_es.sh"
backup_file="${es_dir}/launch.backup"
launcher="${es_dir}/launch.sh"

[ -f "${prev_version}" ] && rm -rf "${prev_version}"
[ -f "${backup_file}" ] && rm -rf "${backup_file}"
[ -f "${launcher}" ] && sed -i '/playlist_es.sh/d' "${launcher}"

sed -i '8i[ -f "/media/project_eris/etc/project_eris/SUP/emulationstation/playlist_es.sh" ] && sh "/media/project_eris/etc/project_eris/SUP/emulationstation/playlist_es.sh"' "${es_dir}/launch.sh"

if ! grep -q "CUSTOM GLOBAL VARIABLES" "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"; then
  sed -i '103i;## CUSTOM GLOBAL VARIABLES ##################################################;' "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"
  sed -i '105i;' "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"
fi
if ! grep -q "GAME_PATH" "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"; then
  sed -i '106i;Location of games path \
GAME_PATH="${MOUNTPOINT}/games"' "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"
fi
if ! grep -q "ROMS_PATH" "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"; then
  sed -i '106i;Location of roms path \
ROMS_PATH="${MOUNTPOINT}/roms"' "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"
fi
if ! grep -q "REGION" "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"; then
  sed -i '106i;System region \
REGION="$(cat "${GAADATA}/geninfo/REGION")"' "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"
fi
if ! grep -q "GAADATA=" "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"; then
  sed -i '106i;Location of gaadata path \
GAADATA="/gaadata"' "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"
fi
if ! grep -q "VOLATILE=" "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"; then
  sed -i '106i;Location of volatile path \
VOLATILE="/var/volatile"' "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"
fi
if ! grep -q "ES_CFG_PATH" "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"; then
  sed -i '106i;Location of Emulationstation configuration files \
ES_CFG_PATH="${PROJECT_ERIS_PATH}/opt/emulationstation/.emulationstation"' "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"
fi
if ! grep -q "EMULATIONSTATION_PATH" "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"; then
  sed -i '106i;Location of Emulationstation \
EMULATIONSTATION_PATH="${PROJECT_ERIS_PATH}/opt/emulationstation"' "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"
fi
if ! grep -q "SUPLEMENTARY_PATH" "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"; then
  sed -i '106i;Location of sound files \
SUPLEMENTARY_PATH="${PROJECT_ERIS_PATH}/etc/project_eris/SUP"' "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"
fi
if ! grep -q "PROJECT_ERIS_ROOT_PATH" "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"; then
  sed -i '106i;Location of Project Eris root \
PROJECT_ERIS_ROOT_PATH="${PROJECT_ERIS_PATH}/etc/project_eris"' "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"
fi
